name: gym-coll
channels:
  - defaults
  - conda-forge
dependencies:
  - gsd
  - numpy
  - scipy
  - openmpi
  - gymnasium
  - sphinx
  - sphinx-rtd-theme
  - pip
  - sphinx-book-theme
  - sphinxcontrib-video
